### ISSUE TITLE
Opening the E2 Code Editor causes "Client 0 Overflowed Reliable Channel"

### ISSUE THREAD

**Issue by EthanWinters2885** [Linus045/e2_vgui_core#24] opened 2023-07-30 22:20 UTC
title says it all,

steps to reproduce:
1. go to "Wire"
2. click on Expression 2
3. open the E2 code editor, any way works

expected result: Code Editor opens like normal
actual result: Code Editor opens for a second before GMod goes Client 0 Overflowed Reliable Channel

**Comment by Linus045** [comment] 2023-07-30 22:57
I can't seem to reproduce the issue on my end.
It might be a weird combination of addons that causes this problem.

1. Are you seeing any error in the console before/after the "Client 0 Overflowed Reliable Channel" message?
2. Can you try to remove all addons except wiremod and e2_vgui_core and try again?

**Comment by EthanWinters2885** [comment] 2023-07-30 23:03
No errors in the console

**Comment by Linus045** [comment] 2023-07-30 23:16
As mentioned before, I'm unable to reproduce the issue myself.
Unless you have some error message relating to my addon or find a way to reliably reproduce the error with the only addons installed being wire and e2_vgui_core I sadly can't do anything.

Therefore I'll close this Issue but feel free to reopen it once you have more info and I will gladly take another look.

**Closed by Linus045** 2023-07-30 23:16 UTC
